baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cluttered Cabinet'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]

# Appearance settings
theme = 'auto'
colorPalette = 'catpuccin'

# Collection to display on home
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2006 6 02'

# Breadcrumbs
breadcrumbs = true


# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'